version: "2.2"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports: 
    #   - "3306:3306"
    mem_limit: 1000000000
    environment:
      MYSQL_DATABASE: acupuncture
      MYSQL_ROOT_PASSWORD: mypasswd
    networks:
      app_net:
        ipv4_address: 172.10.10.10
    volumes:
      - ./docker/mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports: 
      - "8080:8080"
    mem_limit: 500000000
    networks:
      app_net:
        ipv4_address: 172.10.10.11
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.10.10.0/24"
